# Generated by Django 2.0.6 on 2018-06-19 18:17

from django.db import migrations, models
import django.db.models.deletion
import labelsquad.django_postgres_geometry.fields
import labelsquad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', labelsquad.django_postgres_geometry.fields.BoxField(null=True)),
                ('path', labelsquad.django_postgres_geometry.fields.PathField(null=True)),
                ('polygon', labelsquad.django_postgres_geometry.fields.PolygonField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Class type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelsquad.Collection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelsquad.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[(labelsquad.models.ClassTypeChoices('Polygon'), 'Polygon'), (labelsquad.models.ClassTypeChoices('Whole image'), 'Whole image')], default=labelsquad.models.ClassTypeChoices('Polygon'), max_length=1)),
                ('name', models.CharField(max_length=200, verbose_name='Class type')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='can_edit',
            field=models.ManyToManyField(to='labelsquad.Editor'),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to='labelsquad.Editor'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labelsquad.Editor'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='classes',
            field=models.ManyToManyField(to='labelsquad.ObjectClass'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labelsquad.Image'),
        ),
    ]
