# Generated by Django 2.0.6 on 2018-06-20 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labelsquad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Class type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('can_edit', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(to='labelsquad.ObjectClass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Class type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('can_edit', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('collections', models.ManyToManyField(to='labelsquad.ImageCollection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelsquad.ImageCollection'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
