# Generated by Django 2.0.6 on 2018-06-20 14:13

from django.db import migrations, models
import labelsquad.models


class Migration(migrations.Migration):

    dependencies = [
        ('labelsquad', '0002_auto_20180619_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name   '),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='class_type',
            field=models.CharField(choices=[(labelsquad.models.ClassTypeChoices('Polygon'), 'Polygon'), (labelsquad.models.ClassTypeChoices('Whole image'), 'Whole image')], default=labelsquad.models.ClassTypeChoices('Polygon'), max_length=20),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
