# Generated by Django 2.0.6 on 2018-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelsquad', '0005_auto_20180620_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='classes',
            field=models.ManyToManyField(blank=True, to='labelsquad.ObjectClass'),
        ),
    ]
