# Generated by Django 2.0.6 on 2018-06-20 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('labelsquad', '0006_auto_20180620_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 37, 30, 94109, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 37, 41, 166544, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
    ]
